%% PROJECT-SPECIFIC VARIABLES (REVIEW)
myProject = "MBARC_LMR";
collectionSTR = "MBARC_LMR_";
mySource = "Scripps Institution of Oceanography";
mySponsors = "Scripps Institution of Oceanography;NOAA SEFSC";
myFunders = "US Navy Fleet Forces Command;Naval Facilities Engineering Command;US Navy Living Marine Resources";
myScientists = "John Hildebrand;Sean Wiggins;Andrew Read";
DATA_COMMENT = ["This dataset includes raw acoustic recordings from each annual deployment over the 2020-2025 period," + ...
    " plus associated HARP deployments from the 2018-2020 period. In addition to the raw acoustic recordings," + ...
    "there are several associated files for these data which include calibration files (transfer functions) " + ...
    "and Long-term Spectral Averages (LTSAs) for sound exploration and accessibility. Three readme files provide " + ...
    "details on the acoustic recording\u2018s xwav format, LTSA format, and transfer function descriptions. " + ...
    "All recordings are collected in UTC."];
seaArea = "North Pacific Ocean";

%% PARAGRAPHS FOR DATA FIELDS (Edit Optional)
purpose = "Acoustic data was collected at this site provide information on the presence of marine mammals " + ...
    "and anthropogenic sound sources.";

quality_Objectives = "Quality assessments are conducted on every HARP dataset to ensure acoustic recordings are " + ...
    "of high quality and to document any potential problems that may arise during a deployment that may " + ...
    "affect marine mammal occurrence and soundscape analyses. A HARP dataset is considered ready for analysis " + ...
    "when XWAV and LTSA files have been generated, quality checks have been completed, and any potential " + ...
    "errors have been noted with comments and plots associated with the deployment recordings.";

quality_Methods = "HARPs are high-sensitivity, low noise, carefully-calibrated instruments capable of recording" + ...
    " continuous, high-quality acoustic data over the 10 Hz to 150 kHz frequency band. Typical deployment " + ...
    "durations range from 6 to 18 months. HARPs are continuously maintained and developed to minimize " + ...
    "self-noise, refine calibration and improve sensitivity, ensure timing accuracy, and minimize power " + ...
    "consumption. To ensure data are of the highest quality, multiple steps of data quality control are " + ...
    "undertaken during data processing.  Although rare, any issues with the data are documented when " + ...
    "observed. The processing steps and quality checks are as follows.\n\nHARP acoustic recordings are " + ...
    "recovered from field equipment in compressed proprietary .hrp format. A standard HARP deployment is " + ...
    "approximately one year in duration with recordings written on between 8 and 16 raw \u201cdisks\u201d " + ...
    "of the HARP\u2019s internal storage. After a HARP is recovered, a process is initiated to generate " + ...
    "image files of the raw disks and decompress the recordings into XWAV format working files (see" + ...
    " XWAV_read_me). Recording timing is checked during file header creation to identify any timing related" + ...
    " recording errors. \n\nAutomated spot checks are run to extract ten randomly identified 10 second" + ...
    " sections per disk, and these are visually examined to verify that the recordings look real " + ...
    "(e.g. contain airgun signals or marine mammal echolocation) and confirm that there are no potential" + ...
    " problems such as tones, system noise or hydrophone failure. Once XWAVs have been created, " + ...
    "Long Term Spectral Averages (LTSAs, see LTSA_read_me) are generated for each raw disk. " + ...
    "These serve as a visual index and averaged representation of the acoustic data. LTSAs are " + ...
    "scanned visually and problems are noted in Comments if found.\n\nHARP recordings cover a broad" + ...
    " range of frequencies and serve many different types of users. Recordings are not removed from " + ...
    "the dataset unless they are determined to be entirely unusable for all cases. Issues that affect" + ...
    " a specific frequency range are documented when observed during quality assessment steps. " + ...
    " Due to the large size of these datasets, quality checks are based on subsets and averages of " + ...
    "the data, rather than a detailed review, therefore undocumented data quality issues may exist " + ...
    "within a dataset. The user should also be aware of potential nonstandard periods in the data, " + ...
    "which may not be documented during quality checks. These can include deck tests, used to verify " + ...
    "that a system is working properly prior to deployment, noise related to deployment and recovery " + ...
    "operations, and minor mooring strum. Although most HARP datasets are fully continuous, data gaps" + ...
    " can occasionally occur, and therefore true recording effort should be verified when comparing " + ...
    "quantities of detections over time. ";
  